// Auto-generated by scripts/build_assets_tab_data.py
// Do not edit directly. Re-run script to update.

export interface AssetCategoryItem {
  category: string;
  count: number;
  percentage: number;
  type: 'core' | 'supporting';
}

export interface AssetRingSlice {
  name: string;
  count: number;
  percentage: number;
  color: string;
}

export interface StateAssetItem {
  state: string;
  core: number;
  supporting: number;
  total: number;
  corePercentage: number;
  supportingPercentage: number;
}

export interface TourismAssetKpis {
  coreAssetsCount: number;
  supportingAssetsCount: number;
  totalAssetsCount: number;
  categoryCount: number;
  subCategoryCount: number;
  statesCoveredCount: number;
}

export const TOURISM_ASSETS_KPIS: TourismAssetKpis = {
  coreAssetsCount: 5491,
  supportingAssetsCount: 55240,
  totalAssetsCount: 60731,
  categoryCount: 9,
  subCategoryCount: 50,
  statesCoveredCount: 16,
};

export const ASSET_BREAKDOWN_ALL: AssetCategoryItem[] = [
  {
    "category": "Food & Beverage",
    "count": 28462,
    "percentage": 46.9,
    "type": "supporting"
  },
  {
    "category": "Public Transport",
    "count": 15748,
    "percentage": 25.9,
    "type": "supporting"
  },
  {
    "category": "Accommodation",
    "count": 6281,
    "percentage": 10.3,
    "type": "supporting"
  },
  {
    "category": "Healthcare & Essential",
    "count": 4749,
    "percentage": 7.8,
    "type": "supporting"
  },
  {
    "category": "Nature & Outdoors",
    "count": 2076,
    "percentage": 3.4,
    "type": "core"
  },
  {
    "category": "Heritage & Culture",
    "count": 1868,
    "percentage": 3.1,
    "type": "core"
  },
  {
    "category": "Attractions & Landmarks",
    "count": 1044,
    "percentage": 1.7,
    "type": "core"
  },
  {
    "category": "Museums & Galleries",
    "count": 356,
    "percentage": 0.6,
    "type": "core"
  },
  {
    "category": "Amusement & Wildlife",
    "count": 147,
    "percentage": 0.2,
    "type": "core"
  }
];

export const ASSET_BREAKDOWN_CORE: AssetCategoryItem[] = [
  {
    "category": "Nature & Outdoors",
    "count": 2076,
    "percentage": 37.8,
    "type": "core"
  },
  {
    "category": "Heritage & Culture",
    "count": 1868,
    "percentage": 34.0,
    "type": "core"
  },
  {
    "category": "Attractions & Landmarks",
    "count": 1044,
    "percentage": 19.0,
    "type": "core"
  },
  {
    "category": "Museums & Galleries",
    "count": 356,
    "percentage": 6.5,
    "type": "core"
  },
  {
    "category": "Amusement & Wildlife",
    "count": 147,
    "percentage": 2.7,
    "type": "core"
  }
];

export const ASSET_BREAKDOWN_SUPPORTING: AssetCategoryItem[] = [
  {
    "category": "Food & Beverage",
    "count": 28462,
    "percentage": 51.5,
    "type": "supporting"
  },
  {
    "category": "Public Transport",
    "count": 15748,
    "percentage": 28.5,
    "type": "supporting"
  },
  {
    "category": "Accommodation",
    "count": 6281,
    "percentage": 11.4,
    "type": "supporting"
  },
  {
    "category": "Healthcare & Essential",
    "count": 4749,
    "percentage": 8.6,
    "type": "supporting"
  }
];

export const CORE_ASSET_MIX: AssetRingSlice[] = [
  {
    "name": "Nature & Outdoors",
    "count": 2076,
    "percentage": 37.8,
    "color": "#059669"
  },
  {
    "name": "Heritage & Culture",
    "count": 1868,
    "percentage": 34.0,
    "color": "#d97706"
  },
  {
    "name": "Attractions & Landmarks",
    "count": 1044,
    "percentage": 19.0,
    "color": "#2563eb"
  },
  {
    "name": "Museums & Galleries",
    "count": 356,
    "percentage": 6.5,
    "color": "#7c3aed"
  },
  {
    "name": "Amusement & Wildlife",
    "count": 147,
    "percentage": 2.7,
    "color": "#ec4899"
  }
];

export const SUPPORTING_ASSET_MIX: AssetRingSlice[] = [
  {
    "name": "Food & Beverage",
    "count": 28462,
    "percentage": 51.5,
    "color": "#ea580c"
  },
  {
    "name": "Public Transport",
    "count": 15748,
    "percentage": 28.5,
    "color": "#0284c7"
  },
  {
    "name": "Accommodation",
    "count": 6281,
    "percentage": 11.4,
    "color": "#4f46e5"
  },
  {
    "name": "Healthcare & Essential",
    "count": 4749,
    "percentage": 8.6,
    "color": "#dc2626"
  }
];

export const STATE_ASSETS_TOTAL: StateAssetItem[] = [
  {
    "state": "Selangor",
    "core": 493,
    "supporting": 13050,
    "total": 13543,
    "corePercentage": 3.6,
    "supportingPercentage": 96.4
  },
  {
    "state": "W.P. Kuala Lumpur",
    "core": 239,
    "supporting": 7727,
    "total": 7966,
    "corePercentage": 3.0,
    "supportingPercentage": 97.0
  },
  {
    "state": "Johor",
    "core": 351,
    "supporting": 6689,
    "total": 7040,
    "corePercentage": 5.0,
    "supportingPercentage": 95.0
  },
  {
    "state": "Pulau Pinang",
    "core": 374,
    "supporting": 5170,
    "total": 5544,
    "corePercentage": 6.7,
    "supportingPercentage": 93.3
  },
  {
    "state": "Sarawak",
    "core": 474,
    "supporting": 4795,
    "total": 5269,
    "corePercentage": 9.0,
    "supportingPercentage": 91.0
  },
  {
    "state": "Perak",
    "core": 403,
    "supporting": 3471,
    "total": 3874,
    "corePercentage": 10.4,
    "supportingPercentage": 89.6
  },
  {
    "state": "Kedah",
    "core": 335,
    "supporting": 2792,
    "total": 3127,
    "corePercentage": 10.7,
    "supportingPercentage": 89.3
  },
  {
    "state": "Pahang",
    "core": 456,
    "supporting": 2517,
    "total": 2973,
    "corePercentage": 15.3,
    "supportingPercentage": 84.7
  },
  {
    "state": "Sabah",
    "core": 449,
    "supporting": 2439,
    "total": 2888,
    "corePercentage": 15.5,
    "supportingPercentage": 84.5
  },
  {
    "state": "Melaka",
    "core": 1202,
    "supporting": 1656,
    "total": 2858,
    "corePercentage": 42.1,
    "supportingPercentage": 57.9
  },
  {
    "state": "Kelantan",
    "core": 213,
    "supporting": 1598,
    "total": 1811,
    "corePercentage": 11.8,
    "supportingPercentage": 88.2
  },
  {
    "state": "Negeri Sembilan",
    "core": 169,
    "supporting": 1494,
    "total": 1663,
    "corePercentage": 10.2,
    "supportingPercentage": 89.8
  },
  {
    "state": "Terengganu",
    "core": 270,
    "supporting": 1283,
    "total": 1553,
    "corePercentage": 17.4,
    "supportingPercentage": 82.6
  },
  {
    "state": "W.P. Putrajaya",
    "core": 12,
    "supporting": 290,
    "total": 302,
    "corePercentage": 4.0,
    "supportingPercentage": 96.0
  },
  {
    "state": "Perlis",
    "core": 15,
    "supporting": 179,
    "total": 194,
    "corePercentage": 7.7,
    "supportingPercentage": 92.3
  },
  {
    "state": "W.P. Labuan",
    "core": 36,
    "supporting": 90,
    "total": 126,
    "corePercentage": 28.6,
    "supportingPercentage": 71.4
  }
];

export const STATE_ASSETS_CORE: StateAssetItem[] = [
  {
    "state": "Melaka",
    "core": 1202,
    "supporting": 1656,
    "total": 2858,
    "corePercentage": 42.1,
    "supportingPercentage": 57.9
  },
  {
    "state": "Selangor",
    "core": 493,
    "supporting": 13050,
    "total": 13543,
    "corePercentage": 3.6,
    "supportingPercentage": 96.4
  },
  {
    "state": "Sarawak",
    "core": 474,
    "supporting": 4795,
    "total": 5269,
    "corePercentage": 9.0,
    "supportingPercentage": 91.0
  },
  {
    "state": "Pahang",
    "core": 456,
    "supporting": 2517,
    "total": 2973,
    "corePercentage": 15.3,
    "supportingPercentage": 84.7
  },
  {
    "state": "Sabah",
    "core": 449,
    "supporting": 2439,
    "total": 2888,
    "corePercentage": 15.5,
    "supportingPercentage": 84.5
  },
  {
    "state": "Perak",
    "core": 403,
    "supporting": 3471,
    "total": 3874,
    "corePercentage": 10.4,
    "supportingPercentage": 89.6
  },
  {
    "state": "Pulau Pinang",
    "core": 374,
    "supporting": 5170,
    "total": 5544,
    "corePercentage": 6.7,
    "supportingPercentage": 93.3
  },
  {
    "state": "Johor",
    "core": 351,
    "supporting": 6689,
    "total": 7040,
    "corePercentage": 5.0,
    "supportingPercentage": 95.0
  },
  {
    "state": "Kedah",
    "core": 335,
    "supporting": 2792,
    "total": 3127,
    "corePercentage": 10.7,
    "supportingPercentage": 89.3
  },
  {
    "state": "Terengganu",
    "core": 270,
    "supporting": 1283,
    "total": 1553,
    "corePercentage": 17.4,
    "supportingPercentage": 82.6
  },
  {
    "state": "W.P. Kuala Lumpur",
    "core": 239,
    "supporting": 7727,
    "total": 7966,
    "corePercentage": 3.0,
    "supportingPercentage": 97.0
  },
  {
    "state": "Kelantan",
    "core": 213,
    "supporting": 1598,
    "total": 1811,
    "corePercentage": 11.8,
    "supportingPercentage": 88.2
  },
  {
    "state": "Negeri Sembilan",
    "core": 169,
    "supporting": 1494,
    "total": 1663,
    "corePercentage": 10.2,
    "supportingPercentage": 89.8
  },
  {
    "state": "W.P. Labuan",
    "core": 36,
    "supporting": 90,
    "total": 126,
    "corePercentage": 28.6,
    "supportingPercentage": 71.4
  },
  {
    "state": "Perlis",
    "core": 15,
    "supporting": 179,
    "total": 194,
    "corePercentage": 7.7,
    "supportingPercentage": 92.3
  },
  {
    "state": "W.P. Putrajaya",
    "core": 12,
    "supporting": 290,
    "total": 302,
    "corePercentage": 4.0,
    "supportingPercentage": 96.0
  }
];

export const STATE_ASSETS_SUPPORTING: StateAssetItem[] = [
  {
    "state": "Selangor",
    "core": 493,
    "supporting": 13050,
    "total": 13543,
    "corePercentage": 3.6,
    "supportingPercentage": 96.4
  },
  {
    "state": "W.P. Kuala Lumpur",
    "core": 239,
    "supporting": 7727,
    "total": 7966,
    "corePercentage": 3.0,
    "supportingPercentage": 97.0
  },
  {
    "state": "Johor",
    "core": 351,
    "supporting": 6689,
    "total": 7040,
    "corePercentage": 5.0,
    "supportingPercentage": 95.0
  },
  {
    "state": "Pulau Pinang",
    "core": 374,
    "supporting": 5170,
    "total": 5544,
    "corePercentage": 6.7,
    "supportingPercentage": 93.3
  },
  {
    "state": "Sarawak",
    "core": 474,
    "supporting": 4795,
    "total": 5269,
    "corePercentage": 9.0,
    "supportingPercentage": 91.0
  },
  {
    "state": "Perak",
    "core": 403,
    "supporting": 3471,
    "total": 3874,
    "corePercentage": 10.4,
    "supportingPercentage": 89.6
  },
  {
    "state": "Kedah",
    "core": 335,
    "supporting": 2792,
    "total": 3127,
    "corePercentage": 10.7,
    "supportingPercentage": 89.3
  },
  {
    "state": "Pahang",
    "core": 456,
    "supporting": 2517,
    "total": 2973,
    "corePercentage": 15.3,
    "supportingPercentage": 84.7
  },
  {
    "state": "Sabah",
    "core": 449,
    "supporting": 2439,
    "total": 2888,
    "corePercentage": 15.5,
    "supportingPercentage": 84.5
  },
  {
    "state": "Melaka",
    "core": 1202,
    "supporting": 1656,
    "total": 2858,
    "corePercentage": 42.1,
    "supportingPercentage": 57.9
  },
  {
    "state": "Kelantan",
    "core": 213,
    "supporting": 1598,
    "total": 1811,
    "corePercentage": 11.8,
    "supportingPercentage": 88.2
  },
  {
    "state": "Negeri Sembilan",
    "core": 169,
    "supporting": 1494,
    "total": 1663,
    "corePercentage": 10.2,
    "supportingPercentage": 89.8
  },
  {
    "state": "Terengganu",
    "core": 270,
    "supporting": 1283,
    "total": 1553,
    "corePercentage": 17.4,
    "supportingPercentage": 82.6
  },
  {
    "state": "W.P. Putrajaya",
    "core": 12,
    "supporting": 290,
    "total": 302,
    "corePercentage": 4.0,
    "supportingPercentage": 96.0
  },
  {
    "state": "Perlis",
    "core": 15,
    "supporting": 179,
    "total": 194,
    "corePercentage": 7.7,
    "supportingPercentage": 92.3
  },
  {
    "state": "W.P. Labuan",
    "core": 36,
    "supporting": 90,
    "total": 126,
    "corePercentage": 28.6,
    "supportingPercentage": 71.4
  }
];

export interface StateAssetDensityItem {
  id: string;
  name: string;
  coreAssets: number;
  supportingAssets: number;
  totalAssets: number;
  landAreaKm2: number;
  coreDensity: number;
  supportingDensity: number;
}

export const STATE_ASSET_DENSITY_DATA: Record<string, StateAssetDensityItem> = {
  "selangor": {
    "id": "selangor",
    "name": "Selangor",
    "coreAssets": 493,
    "supportingAssets": 13050,
    "totalAssets": 13543,
    "landAreaKm2": 7990.42,
    "coreDensity": 61.7,
    "supportingDensity": 1633.21
  },
  "kuala_lumpur": {
    "id": "kuala_lumpur",
    "name": "W.P. Kuala Lumpur",
    "coreAssets": 239,
    "supportingAssets": 7727,
    "totalAssets": 7966,
    "landAreaKm2": 244.7,
    "coreDensity": 976.71,
    "supportingDensity": 31577.44
  },
  "perak": {
    "id": "perak",
    "name": "Perak",
    "coreAssets": 403,
    "supportingAssets": 3471,
    "totalAssets": 3874,
    "landAreaKm2": 21256.94,
    "coreDensity": 18.96,
    "supportingDensity": 163.29
  },
  "pahang": {
    "id": "pahang",
    "name": "Pahang",
    "coreAssets": 456,
    "supportingAssets": 2517,
    "totalAssets": 2973,
    "landAreaKm2": 36349.84,
    "coreDensity": 12.54,
    "supportingDensity": 69.24
  },
  "sarawak": {
    "id": "sarawak",
    "name": "Sarawak",
    "coreAssets": 474,
    "supportingAssets": 4795,
    "totalAssets": 5269,
    "landAreaKm2": 125154.79,
    "coreDensity": 3.79,
    "supportingDensity": 38.31
  },
  "sabah": {
    "id": "sabah",
    "name": "Sabah",
    "coreAssets": 449,
    "supportingAssets": 2439,
    "totalAssets": 2888,
    "landAreaKm2": 75320.11,
    "coreDensity": 5.96,
    "supportingDensity": 32.38
  },
  "melaka": {
    "id": "melaka",
    "name": "Melaka",
    "coreAssets": 1202,
    "supportingAssets": 1656,
    "totalAssets": 2858,
    "landAreaKm2": 1660.66,
    "coreDensity": 723.81,
    "supportingDensity": 997.19
  },
  "negeri_sembilan": {
    "id": "negeri_sembilan",
    "name": "Negeri Sembilan",
    "coreAssets": 169,
    "supportingAssets": 1494,
    "totalAssets": 1663,
    "landAreaKm2": 6741.41,
    "coreDensity": 25.07,
    "supportingDensity": 221.62
  },
  "johor": {
    "id": "johor",
    "name": "Johor",
    "coreAssets": 351,
    "supportingAssets": 6689,
    "totalAssets": 7040,
    "landAreaKm2": 19299.21,
    "coreDensity": 18.19,
    "supportingDensity": 346.59
  },
  "penang": {
    "id": "penang",
    "name": "Pulau Pinang",
    "coreAssets": 374,
    "supportingAssets": 5170,
    "totalAssets": 5544,
    "landAreaKm2": 1060.22,
    "coreDensity": 352.76,
    "supportingDensity": 4876.35
  },
  "kedah": {
    "id": "kedah",
    "name": "Kedah",
    "coreAssets": 335,
    "supportingAssets": 2792,
    "totalAssets": 3127,
    "landAreaKm2": 9627.19,
    "coreDensity": 34.8,
    "supportingDensity": 290.01
  },
  "terengganu": {
    "id": "terengganu",
    "name": "Terengganu",
    "coreAssets": 270,
    "supportingAssets": 1283,
    "totalAssets": 1553,
    "landAreaKm2": 13097.57,
    "coreDensity": 20.61,
    "supportingDensity": 97.96
  },
  "kelantan": {
    "id": "kelantan",
    "name": "Kelantan",
    "coreAssets": 213,
    "supportingAssets": 1598,
    "totalAssets": 1811,
    "landAreaKm2": 15353.11,
    "coreDensity": 13.87,
    "supportingDensity": 104.08
  },
  "perlis": {
    "id": "perlis",
    "name": "Perlis",
    "coreAssets": 15,
    "supportingAssets": 179,
    "totalAssets": 194,
    "landAreaKm2": 833.77,
    "coreDensity": 17.99,
    "supportingDensity": 214.69
  },
  "putrajaya": {
    "id": "putrajaya",
    "name": "W.P. Putrajaya",
    "coreAssets": 12,
    "supportingAssets": 290,
    "totalAssets": 302,
    "landAreaKm2": 49.76,
    "coreDensity": 241.16,
    "supportingDensity": 5827.97
  },
  "labuan": {
    "id": "labuan",
    "name": "W.P. Labuan",
    "coreAssets": 36,
    "supportingAssets": 90,
    "totalAssets": 126,
    "landAreaKm2": 93.14,
    "coreDensity": 386.51,
    "supportingDensity": 966.29
  }
};

export interface StateAssetMixItem {
  id: string;
  name: string;
  totalCore: number;
  totalSupporting: number;
  totalAssets: number;
  coreMix: AssetRingSlice[];
  supportingMix: AssetRingSlice[];
}

export const STATE_ASSET_MIX_DATA: Record<string, StateAssetMixItem> = {
  "selangor": {
    "id": "selangor",
    "name": "Selangor",
    "totalCore": 493,
    "totalSupporting": 13050,
    "totalAssets": 13543,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 283,
        "percentage": 57.4,
        "color": "#059669"
      },
      {
        "name": "Heritage & Culture",
        "count": 84,
        "percentage": 17.0,
        "color": "#d97706"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 69,
        "percentage": 14.0,
        "color": "#2563eb"
      },
      {
        "name": "Museums & Galleries",
        "count": 30,
        "percentage": 6.1,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 27,
        "percentage": 5.5,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 5816,
        "percentage": 44.6,
        "color": "#ea580c"
      },
      {
        "name": "Public Transport",
        "count": 5573,
        "percentage": 42.7,
        "color": "#0284c7"
      },
      {
        "name": "Healthcare & Essential",
        "count": 1122,
        "percentage": 8.6,
        "color": "#dc2626"
      },
      {
        "name": "Accommodation",
        "count": 539,
        "percentage": 4.1,
        "color": "#4f46e5"
      }
    ]
  },
  "kuala_lumpur": {
    "id": "kuala_lumpur",
    "name": "W.P. Kuala Lumpur",
    "totalCore": 239,
    "totalSupporting": 7727,
    "totalAssets": 7966,
    "coreMix": [
      {
        "name": "Heritage & Culture",
        "count": 67,
        "percentage": 28.0,
        "color": "#d97706"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 56,
        "percentage": 23.4,
        "color": "#2563eb"
      },
      {
        "name": "Museums & Galleries",
        "count": 56,
        "percentage": 23.4,
        "color": "#7c3aed"
      },
      {
        "name": "Nature & Outdoors",
        "count": 53,
        "percentage": 22.2,
        "color": "#059669"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 7,
        "percentage": 2.9,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 4405,
        "percentage": 57.0,
        "color": "#ea580c"
      },
      {
        "name": "Public Transport",
        "count": 2016,
        "percentage": 26.1,
        "color": "#0284c7"
      },
      {
        "name": "Healthcare & Essential",
        "count": 670,
        "percentage": 8.7,
        "color": "#dc2626"
      },
      {
        "name": "Accommodation",
        "count": 636,
        "percentage": 8.2,
        "color": "#4f46e5"
      }
    ]
  },
  "perak": {
    "id": "perak",
    "name": "Perak",
    "totalCore": 403,
    "totalSupporting": 3471,
    "totalAssets": 3874,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 208,
        "percentage": 51.6,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 77,
        "percentage": 19.1,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 63,
        "percentage": 15.6,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 44,
        "percentage": 10.9,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 11,
        "percentage": 2.7,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 1714,
        "percentage": 49.4,
        "color": "#ea580c"
      },
      {
        "name": "Public Transport",
        "count": 898,
        "percentage": 25.9,
        "color": "#0284c7"
      },
      {
        "name": "Accommodation",
        "count": 484,
        "percentage": 13.9,
        "color": "#4f46e5"
      },
      {
        "name": "Healthcare & Essential",
        "count": 375,
        "percentage": 10.8,
        "color": "#dc2626"
      }
    ]
  },
  "pahang": {
    "id": "pahang",
    "name": "Pahang",
    "totalCore": 456,
    "totalSupporting": 2517,
    "totalAssets": 2973,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 248,
        "percentage": 54.4,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 100,
        "percentage": 21.9,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 77,
        "percentage": 16.9,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 17,
        "percentage": 3.7,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 14,
        "percentage": 3.1,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 1127,
        "percentage": 44.8,
        "color": "#ea580c"
      },
      {
        "name": "Public Transport",
        "count": 629,
        "percentage": 25.0,
        "color": "#0284c7"
      },
      {
        "name": "Accommodation",
        "count": 571,
        "percentage": 22.7,
        "color": "#4f46e5"
      },
      {
        "name": "Healthcare & Essential",
        "count": 190,
        "percentage": 7.5,
        "color": "#dc2626"
      }
    ]
  },
  "sarawak": {
    "id": "sarawak",
    "name": "Sarawak",
    "totalCore": 474,
    "totalSupporting": 4795,
    "totalAssets": 5269,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 212,
        "percentage": 44.7,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 122,
        "percentage": 25.7,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 111,
        "percentage": 23.4,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 23,
        "percentage": 4.9,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 6,
        "percentage": 1.3,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 3263,
        "percentage": 68.1,
        "color": "#ea580c"
      },
      {
        "name": "Accommodation",
        "count": 819,
        "percentage": 17.1,
        "color": "#4f46e5"
      },
      {
        "name": "Healthcare & Essential",
        "count": 415,
        "percentage": 8.7,
        "color": "#dc2626"
      },
      {
        "name": "Public Transport",
        "count": 298,
        "percentage": 6.2,
        "color": "#0284c7"
      }
    ]
  },
  "sabah": {
    "id": "sabah",
    "name": "Sabah",
    "totalCore": 449,
    "totalSupporting": 2439,
    "totalAssets": 2888,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 182,
        "percentage": 40.5,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 169,
        "percentage": 37.6,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 66,
        "percentage": 14.7,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 23,
        "percentage": 5.1,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 9,
        "percentage": 2.0,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 1260,
        "percentage": 51.7,
        "color": "#ea580c"
      },
      {
        "name": "Accommodation",
        "count": 533,
        "percentage": 21.9,
        "color": "#4f46e5"
      },
      {
        "name": "Public Transport",
        "count": 457,
        "percentage": 18.7,
        "color": "#0284c7"
      },
      {
        "name": "Healthcare & Essential",
        "count": 189,
        "percentage": 7.7,
        "color": "#dc2626"
      }
    ]
  },
  "melaka": {
    "id": "melaka",
    "name": "Melaka",
    "totalCore": 1202,
    "totalSupporting": 1656,
    "totalAssets": 2858,
    "coreMix": [
      {
        "name": "Heritage & Culture",
        "count": 1072,
        "percentage": 89.2,
        "color": "#d97706"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 39,
        "percentage": 3.2,
        "color": "#2563eb"
      },
      {
        "name": "Museums & Galleries",
        "count": 38,
        "percentage": 3.2,
        "color": "#7c3aed"
      },
      {
        "name": "Nature & Outdoors",
        "count": 36,
        "percentage": 3.0,
        "color": "#059669"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 17,
        "percentage": 1.4,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 1002,
        "percentage": 60.5,
        "color": "#ea580c"
      },
      {
        "name": "Public Transport",
        "count": 289,
        "percentage": 17.5,
        "color": "#0284c7"
      },
      {
        "name": "Accommodation",
        "count": 287,
        "percentage": 17.3,
        "color": "#4f46e5"
      },
      {
        "name": "Healthcare & Essential",
        "count": 78,
        "percentage": 4.7,
        "color": "#dc2626"
      }
    ]
  },
  "negeri_sembilan": {
    "id": "negeri_sembilan",
    "name": "Negeri Sembilan",
    "totalCore": 169,
    "totalSupporting": 1494,
    "totalAssets": 1663,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 101,
        "percentage": 59.8,
        "color": "#059669"
      },
      {
        "name": "Heritage & Culture",
        "count": 31,
        "percentage": 18.3,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 19,
        "percentage": 11.2,
        "color": "#7c3aed"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 12,
        "percentage": 7.1,
        "color": "#2563eb"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 6,
        "percentage": 3.6,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 706,
        "percentage": 47.3,
        "color": "#ea580c"
      },
      {
        "name": "Public Transport",
        "count": 480,
        "percentage": 32.1,
        "color": "#0284c7"
      },
      {
        "name": "Accommodation",
        "count": 167,
        "percentage": 11.2,
        "color": "#4f46e5"
      },
      {
        "name": "Healthcare & Essential",
        "count": 141,
        "percentage": 9.4,
        "color": "#dc2626"
      }
    ]
  },
  "johor": {
    "id": "johor",
    "name": "Johor",
    "totalCore": 351,
    "totalSupporting": 6689,
    "totalAssets": 7040,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 191,
        "percentage": 54.4,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 90,
        "percentage": 25.6,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 31,
        "percentage": 8.8,
        "color": "#d97706"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 23,
        "percentage": 6.6,
        "color": "#ec4899"
      },
      {
        "name": "Museums & Galleries",
        "count": 16,
        "percentage": 4.6,
        "color": "#7c3aed"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 3311,
        "percentage": 49.5,
        "color": "#ea580c"
      },
      {
        "name": "Public Transport",
        "count": 2298,
        "percentage": 34.4,
        "color": "#0284c7"
      },
      {
        "name": "Accommodation",
        "count": 557,
        "percentage": 8.3,
        "color": "#4f46e5"
      },
      {
        "name": "Healthcare & Essential",
        "count": 523,
        "percentage": 7.8,
        "color": "#dc2626"
      }
    ]
  },
  "penang": {
    "id": "penang",
    "name": "Pulau Pinang",
    "totalCore": 374,
    "totalSupporting": 5170,
    "totalAssets": 5544,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 137,
        "percentage": 36.6,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 115,
        "percentage": 30.7,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 66,
        "percentage": 17.6,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 50,
        "percentage": 13.4,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 6,
        "percentage": 1.6,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 2597,
        "percentage": 50.2,
        "color": "#ea580c"
      },
      {
        "name": "Public Transport",
        "count": 1867,
        "percentage": 36.1,
        "color": "#0284c7"
      },
      {
        "name": "Accommodation",
        "count": 386,
        "percentage": 7.5,
        "color": "#4f46e5"
      },
      {
        "name": "Healthcare & Essential",
        "count": 320,
        "percentage": 6.2,
        "color": "#dc2626"
      }
    ]
  },
  "kedah": {
    "id": "kedah",
    "name": "Kedah",
    "totalCore": 335,
    "totalSupporting": 2792,
    "totalAssets": 3127,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 160,
        "percentage": 47.8,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 85,
        "percentage": 25.4,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 55,
        "percentage": 16.4,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 21,
        "percentage": 6.3,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 14,
        "percentage": 4.2,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 1693,
        "percentage": 60.6,
        "color": "#ea580c"
      },
      {
        "name": "Accommodation",
        "count": 446,
        "percentage": 16.0,
        "color": "#4f46e5"
      },
      {
        "name": "Healthcare & Essential",
        "count": 347,
        "percentage": 12.4,
        "color": "#dc2626"
      },
      {
        "name": "Public Transport",
        "count": 306,
        "percentage": 11.0,
        "color": "#0284c7"
      }
    ]
  },
  "terengganu": {
    "id": "terengganu",
    "name": "Terengganu",
    "totalCore": 270,
    "totalSupporting": 1283,
    "totalAssets": 1553,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 192,
        "percentage": 71.1,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 56,
        "percentage": 20.7,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 12,
        "percentage": 4.4,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 7,
        "percentage": 2.6,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 3,
        "percentage": 1.1,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 581,
        "percentage": 45.3,
        "color": "#ea580c"
      },
      {
        "name": "Accommodation",
        "count": 316,
        "percentage": 24.6,
        "color": "#4f46e5"
      },
      {
        "name": "Public Transport",
        "count": 218,
        "percentage": 17.0,
        "color": "#0284c7"
      },
      {
        "name": "Healthcare & Essential",
        "count": 168,
        "percentage": 13.1,
        "color": "#dc2626"
      }
    ]
  },
  "kelantan": {
    "id": "kelantan",
    "name": "Kelantan",
    "totalCore": 213,
    "totalSupporting": 1598,
    "totalAssets": 1811,
    "coreMix": [
      {
        "name": "Heritage & Culture",
        "count": 120,
        "percentage": 56.3,
        "color": "#d97706"
      },
      {
        "name": "Nature & Outdoors",
        "count": 45,
        "percentage": 21.1,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 37,
        "percentage": 17.4,
        "color": "#2563eb"
      },
      {
        "name": "Museums & Galleries",
        "count": 8,
        "percentage": 3.8,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 3,
        "percentage": 1.4,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 757,
        "percentage": 47.4,
        "color": "#ea580c"
      },
      {
        "name": "Accommodation",
        "count": 470,
        "percentage": 29.4,
        "color": "#4f46e5"
      },
      {
        "name": "Public Transport",
        "count": 192,
        "percentage": 12.0,
        "color": "#0284c7"
      },
      {
        "name": "Healthcare & Essential",
        "count": 179,
        "percentage": 11.2,
        "color": "#dc2626"
      }
    ]
  },
  "perlis": {
    "id": "perlis",
    "name": "Perlis",
    "totalCore": 15,
    "totalSupporting": 179,
    "totalAssets": 194,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 10,
        "percentage": 66.7,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 2,
        "percentage": 13.3,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 1,
        "percentage": 6.7,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 1,
        "percentage": 6.7,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 1,
        "percentage": 6.7,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 98,
        "percentage": 54.7,
        "color": "#ea580c"
      },
      {
        "name": "Accommodation",
        "count": 36,
        "percentage": 20.1,
        "color": "#4f46e5"
      },
      {
        "name": "Public Transport",
        "count": 32,
        "percentage": 17.9,
        "color": "#0284c7"
      },
      {
        "name": "Healthcare & Essential",
        "count": 13,
        "percentage": 7.3,
        "color": "#dc2626"
      }
    ]
  },
  "putrajaya": {
    "id": "putrajaya",
    "name": "W.P. Putrajaya",
    "totalCore": 12,
    "totalSupporting": 290,
    "totalAssets": 302,
    "coreMix": [
      {
        "name": "Heritage & Culture",
        "count": 6,
        "percentage": 50.0,
        "color": "#d97706"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 5,
        "percentage": 41.7,
        "color": "#2563eb"
      },
      {
        "name": "Nature & Outdoors",
        "count": 1,
        "percentage": 8.3,
        "color": "#059669"
      },
      {
        "name": "Museums & Galleries",
        "count": 0,
        "percentage": 0.0,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 0,
        "percentage": 0.0,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Public Transport",
        "count": 187,
        "percentage": 64.5,
        "color": "#0284c7"
      },
      {
        "name": "Food & Beverage",
        "count": 87,
        "percentage": 30.0,
        "color": "#ea580c"
      },
      {
        "name": "Healthcare & Essential",
        "count": 9,
        "percentage": 3.1,
        "color": "#dc2626"
      },
      {
        "name": "Accommodation",
        "count": 7,
        "percentage": 2.4,
        "color": "#4f46e5"
      }
    ]
  },
  "labuan": {
    "id": "labuan",
    "name": "W.P. Labuan",
    "totalCore": 36,
    "totalSupporting": 90,
    "totalAssets": 126,
    "coreMix": [
      {
        "name": "Nature & Outdoors",
        "count": 17,
        "percentage": 47.2,
        "color": "#059669"
      },
      {
        "name": "Attractions & Landmarks",
        "count": 10,
        "percentage": 27.8,
        "color": "#2563eb"
      },
      {
        "name": "Heritage & Culture",
        "count": 6,
        "percentage": 16.7,
        "color": "#d97706"
      },
      {
        "name": "Museums & Galleries",
        "count": 3,
        "percentage": 8.3,
        "color": "#7c3aed"
      },
      {
        "name": "Amusement & Wildlife",
        "count": 0,
        "percentage": 0.0,
        "color": "#ec4899"
      }
    ],
    "supportingMix": [
      {
        "name": "Food & Beverage",
        "count": 45,
        "percentage": 50.0,
        "color": "#ea580c"
      },
      {
        "name": "Accommodation",
        "count": 27,
        "percentage": 30.0,
        "color": "#4f46e5"
      },
      {
        "name": "Healthcare & Essential",
        "count": 10,
        "percentage": 11.1,
        "color": "#dc2626"
      },
      {
        "name": "Public Transport",
        "count": 8,
        "percentage": 8.9,
        "color": "#0284c7"
      }
    ]
  }
};

export interface StatePortfolioDiversitySegment {
  category: string;
  count: number;
  percentage: number;
  color: string;
}

export interface StatePortfolioDiversityItem {
  id: string;
  state: string;
  totalCoreAssets: number;
  segments: StatePortfolioDiversitySegment[];
}

export const STATE_PORTFOLIO_DIVERSITY_DATA: StatePortfolioDiversityItem[] = [
  {
    "id": "labuan",
    "state": "W.P. Labuan",
    "totalCoreAssets": 36,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 10,
        "percentage": 27.8,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 6,
        "percentage": 16.7,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 3,
        "percentage": 8.3,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 0,
        "percentage": 0.0,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 17,
        "percentage": 47.2,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "terengganu",
    "state": "Terengganu",
    "totalCoreAssets": 270,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 56,
        "percentage": 20.7,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 12,
        "percentage": 4.4,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 7,
        "percentage": 2.6,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 3,
        "percentage": 1.1,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 192,
        "percentage": 71.1,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "kelantan",
    "state": "Kelantan",
    "totalCoreAssets": 213,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 37,
        "percentage": 17.4,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 120,
        "percentage": 56.3,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 8,
        "percentage": 3.8,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 3,
        "percentage": 1.4,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 45,
        "percentage": 21.1,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "pahang",
    "state": "Pahang",
    "totalCoreAssets": 456,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 100,
        "percentage": 21.9,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 77,
        "percentage": 16.9,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 17,
        "percentage": 3.7,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 14,
        "percentage": 3.1,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 248,
        "percentage": 54.4,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "kedah",
    "state": "Kedah",
    "totalCoreAssets": 335,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 85,
        "percentage": 25.4,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 55,
        "percentage": 16.4,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 21,
        "percentage": 6.3,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 14,
        "percentage": 4.2,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 160,
        "percentage": 47.8,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "johor",
    "state": "Johor",
    "totalCoreAssets": 351,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 90,
        "percentage": 25.6,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 31,
        "percentage": 8.8,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 16,
        "percentage": 4.6,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 23,
        "percentage": 6.6,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 191,
        "percentage": 54.4,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "sarawak",
    "state": "Sarawak",
    "totalCoreAssets": 474,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 122,
        "percentage": 25.7,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 111,
        "percentage": 23.4,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 23,
        "percentage": 4.9,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 6,
        "percentage": 1.3,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 212,
        "percentage": 44.7,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "perlis",
    "state": "Perlis",
    "totalCoreAssets": 15,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 2,
        "percentage": 13.3,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 1,
        "percentage": 6.7,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 1,
        "percentage": 6.7,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 1,
        "percentage": 6.7,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 10,
        "percentage": 66.7,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "sabah",
    "state": "Sabah",
    "totalCoreAssets": 449,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 169,
        "percentage": 37.6,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 66,
        "percentage": 14.7,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 23,
        "percentage": 5.1,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 9,
        "percentage": 2.0,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 182,
        "percentage": 40.5,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "selangor",
    "state": "Selangor",
    "totalCoreAssets": 493,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 69,
        "percentage": 14.0,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 84,
        "percentage": 17.0,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 30,
        "percentage": 6.1,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 27,
        "percentage": 5.5,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 283,
        "percentage": 57.4,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "perak",
    "state": "Perak",
    "totalCoreAssets": 403,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 77,
        "percentage": 19.1,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 63,
        "percentage": 15.6,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 44,
        "percentage": 10.9,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 11,
        "percentage": 2.7,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 208,
        "percentage": 51.6,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "negeri_sembilan",
    "state": "Negeri Sembilan",
    "totalCoreAssets": 169,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 12,
        "percentage": 7.1,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 31,
        "percentage": 18.3,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 19,
        "percentage": 11.2,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 6,
        "percentage": 3.6,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 101,
        "percentage": 59.8,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "penang",
    "state": "Pulau Pinang",
    "totalCoreAssets": 374,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 115,
        "percentage": 30.7,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 66,
        "percentage": 17.6,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 50,
        "percentage": 13.4,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 6,
        "percentage": 1.6,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 137,
        "percentage": 36.6,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "putrajaya",
    "state": "W.P. Putrajaya",
    "totalCoreAssets": 12,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 5,
        "percentage": 41.7,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 6,
        "percentage": 50.0,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 0,
        "percentage": 0.0,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 0,
        "percentage": 0.0,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 1,
        "percentage": 8.3,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "kuala_lumpur",
    "state": "W.P. Kuala Lumpur",
    "totalCoreAssets": 239,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 56,
        "percentage": 23.4,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 67,
        "percentage": 28.0,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 56,
        "percentage": 23.4,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 7,
        "percentage": 2.9,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 53,
        "percentage": 22.2,
        "color": "#dc8522"
      }
    ]
  },
  {
    "id": "melaka",
    "state": "Melaka",
    "totalCoreAssets": 1202,
    "segments": [
      {
        "category": "Attractions & Landmarks",
        "count": 39,
        "percentage": 3.2,
        "color": "#2f4fa8"
      },
      {
        "category": "Heritage & Culture",
        "count": 1072,
        "percentage": 89.2,
        "color": "#169d74"
      },
      {
        "category": "Museums & Galleries",
        "count": 38,
        "percentage": 3.2,
        "color": "#209aa4"
      },
      {
        "category": "Amusement & Wildlife",
        "count": 17,
        "percentage": 1.4,
        "color": "#7c3aed"
      },
      {
        "category": "Nature & Outdoors",
        "count": 36,
        "percentage": 3.0,
        "color": "#dc8522"
      }
    ]
  }
];

export const ASSET_CATEGORY_COLORS: Record<string, string> = {
  'Food & Beverage': '#ea580c',
  'Public Transport': '#0284c7',
  'Accommodation': '#4f46e5',
  'Healthcare & Essential': '#dc2626',
  'Nature & Outdoors': '#059669',
  'Heritage & Culture': '#d97706',
  'Attractions & Landmarks': '#2563eb',
  'Museums & Galleries': '#7c3aed',
  'Amusement & Wildlife': '#ec4899',
};
